IcreCreamParlour/Areas/Admin/Controllers/FlavorController.cs
using IcreCreamParlour.Model.Entities;
using IcreCreamParlour.Service;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace IcreCreamParlour.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class FlavorController : Controller
    {
        private readonly IFlavorService _flavorService;
        private readonly IWebHostEnvironment _hostEnvironment;

        public FlavorController(IFlavorService flavorService, IWebHostEnvironment hostEnvironment)
        {
            _flavorService = flavorService;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index(string strSearching = "")
        {
            var flavors = _flavorService.GetAll();
            if (strSearching != null && strSearching != "")
            {
                flavors = flavors.Where(flavor => flavor.FlavorName.Contains(strSearching)).ToList();
            }
            return View(flavors);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Flavor flavor)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string wwwPath = _hostEnvironment.WebRootPath;
                    string fileName = Path.GetFileNameWithoutExtension(flavor.ImageFile.FileName);
                    string extension = Path.GetExtension(flavor.ImageFile.FileName);
                    flavor.Image = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    string path = Path.Combine(wwwPath + "/Images/flavorimg/", flavor.Image);
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await flavor.ImageFile.CopyToAsync(fileStream);
                    }
                    _flavorService.InsertFlavor(flavor);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            return View(flavor);
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var getFlavorById = _flavorService.FindById(id);
            return View(getFlavorById);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Flavor flavor)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string wwwPath = _hostEnvironment.WebRootPath;
                    string fileName = Path.GetFileNameWithoutExtension(flavor.ImageFile.FileName);
                    string extension = Path.GetExtension(flavor.ImageFile.FileName);
                    flavor.Image = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    string path = Path.Combine(wwwPath + "/Images/flavorimg/", flavor.Image);
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await flavor.ImageFile.CopyToAsync(fileStream);
                    }
                    _flavorService.UpdateFlavor(flavor);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return BadRequest(ModelState);
            }
            return View(flavor);
        }
        public IActionResult Delete(int id)
        {
            _flavorService.DeleteFlavor(id);
            return RedirectToAction("Index");
        }
    }
}

IcreCreamParlour/Areas/Admin/Views/Flavor/Create.cshtml
@model IcreCreamParlour.Model.Entities.Flavor
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h6 class="card-title">Add new flavor</h6>
            <form class="forms-sample" asp-area="Admin" asp-controller="Flavor" asp-action="Create" enctype="multipart/form-data">
                <div class="form-group row">
                    <label asp-for="FlavorName" class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" asp-for="FlavorName" placeholder="FlavorName">
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Ingredients" class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" asp-for="Ingredients" autocomplete="off" placeholder="Ingredients">
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="MakingProcess" class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" asp-for="MakingProcess" placeholder="Description">
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Description" class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" asp-for="Description" placeholder="Description">
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="ImageFile" class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-9">
                        <input type="file" class="icon-file" name="ImageFile" asp-for="ImageFile" accept="images/*">
                    </div>
                </div>
                <button type="submit" class="btn btn-inverse-primary mr-2">Add new</button>
                <a asp-controller="Flavor" asp-action="Index" class="btn btn-inverse-danger">Cancel</a>
            </form>
        </div>
    </div>
</div>

IcreCreamParlour/Areas/Admin/Views/Flavor/Edit.cshtml
@model IcreCreamParlour.Model.Entities.Flavor
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h6 class="card-title">Edit flavor</h6>
            <form class="forms-sample" asp-area="Admin" asp-controller="Flavor" asp-action="Edit" method="post" enctype="multipart/form-data">
                <div class="form-group row" hidden>
                    <label asp-for="FlavorId" class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" asp-for="FlavorId">
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="FlavorName" class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" asp-for="FlavorName" placeholder="FlavorName">
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Ingredients" class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" asp-for="Ingredients" placeholder="Ingredients">
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="MakingProcess" class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" asp-for="MakingProcess" placeholder="MakingProcess">
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Description" class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" asp-for="Description" placeholder="Description">
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="ImageFile" class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-9">
                        <input type="file" class="icon-file" name="ImageFile" asp-for="ImageFile" accept="images/*">
                        <img src="@("~/images/flavorimg/" + Model.Image)" asp-append-version="true" />
                    </div>
                </div>
                <button type="submit" . class="btn btn-inverse-primary mr-2">Edit flavor</button>
                <a asp-controller="Flavor" asp-action="Index" class="btn btn-inverse-danger">Cancel</a>
            </form>
        </div>
    </div>
</div>

IcreCreamParlour/Areas/Admin/Views/Flavor/Index.cshtml
@model IEnumerable<IcreCreamParlour.Model.DTO.FlavorDTO>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="navbar-header">
                    <a asp-action="Create" class="btn btn-outline-danger">Isert flavor</a>
                    <button type="button" class="navbar-toggle collapsed pull-left btn btn-outline-info" data-toggle="collapse" data-target="#navbar-collapse">
                        Search by here
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div> <!-- navbar-header -->
                <div class="collapse navbar-collapse" id="navbar-collapse">
                    <form class="navbar-form navbar-right" role="search" asp-action="Index" method="get">
                        <div class="form-group input-group">
                            <input type="search" class="form-control input-sm" placeholder="Search here ..." id="sitesearch" name="strSearching">
                            <span class="input-group-addon"><button type="submit" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-search"></span></button></span>
                        </div>
                    </form>
                </div>
                <div class="table-responsive">
                    <div id="dataTableExample_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="dataTableExample" class="table dataTable no-footer" role="grid" aria-describedby="dataTableExample_info">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="dataTableExample" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 187.762px;">
                                                @Html.DisplayNameFor(model => model.FlavorId)
                                            </th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTableExample" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 293.487px;">
                                                @Html.DisplayNameFor(model => model.FlavorName)
                                            </th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTableExample" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 134.45px;">
                                                @Html.DisplayNameFor(model => model.Ingredients)
                                            </th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTableExample" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 134.45px;">
                                                @Html.DisplayNameFor(model => model.MakingProcess)
                                            </th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTableExample" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 134.45px;">
                                                @Html.DisplayNameFor(model => model.Description)
                                            </th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTableExample" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 134.45px;">
                                                @Html.DisplayNameFor(model => model.Image)
                                            </th>
                                            <th class="text-center">
                                                Acion
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr role="row" class="odd">
                                                <td class="sorting_1">
                                                    @Html.DisplayFor(modelItem => item.FlavorId)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.FlavorName)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Ingredients)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.MakingProcess)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Description)
                                                </td>
                                                <td>
                                                    <img src="@("~/images/flavorimg/" + item.Image)" asp-append-version="true" />
                                                </td>
                                                <td>
                                                    <a asp-action="Edit" asp-route-id="@item.FlavorId" class="text-warning btn btn-outline-warning">
                                                        <i data-feather="edit-2"></i>
                                                    </a>
                                                    <a asp-action="Delete" asp-route-id="@item.FlavorId" class="text-danger btn btn-outline-danger" onclick="return confirm('Do you want to remove this flavor?')">
                                                        <i data-feather="trash-2"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>